# Generated by Django 6.1 on 2026-08-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_resume_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
