# Generated by Django 6.1 on 2026-08-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='candidates.candidate'),
        ),
    ]
