# Generated by Django 6.1 on 2026-08-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_swipes', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='candidates.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
