# Generated by Django 6.1 on 2026-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_jobswipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobswipe',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobswipe',
            name='decision',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='jobswipe',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_swipe'),
        ),
    ]
