# Generated by Django 6.1 on 2026-08-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
