# Generated by Django 6.1 on 2026-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_remove_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
