# Generated by Django 6.1 on 2026-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_resume_ats_suggestions_resume_extracted_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='probability_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
