# Generated by Django 6.1 on 2026-08-27 11:48

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_resume_probability_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to=candidates.models.resume_upload_path),
        ),
    ]
