# Generated by Django 6.1 on 2026-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_alter_candidate_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
