# Generated by Django 6.1 on 2026-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_resume_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resume_previews/'),
        ),
    ]
