# Generated by Django 6.1 on 2026-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
