# Generated by Django 6.1.1 on 2026-09-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0027_job_live_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('link_opened', 'Application link opened'), ('applied', 'Marked as applied')], db_index=True, default='link_opened', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
