# Generated by Django 5.0.6 on 2026-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='direction',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('save', 'Save')], max_length=5),
        ),
    ]
