services:
  db:
    image: postgres:16
    container_name: swipex_db
    restart: always
    environment:
      POSTGRES_DB: SwipeX_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Praveena$3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: swipx_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: swipx_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: