"""Add constraints without enums

Revision ID: d1ccc37e3941
Revises: 
Create Date: 2026-08-20 20:37:07.811085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ccc37e3941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_token_id'), 'password_reset_tokens', ['token_id'], unique=False)
    op.create_unique_constraint('_user_job_application_uc', 'applications', ['user_id', 'job_id'])
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_unique_constraint('_user_job_recommendation_uc', 'recommendations', ['user_id', 'job_id'])
    op.create_index(op.f('ix_recommendations_job_id'), 'recommendations', ['job_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_swipehistory_job_id'), 'swipehistory', ['job_id'], unique=False)
    op.create_index(op.f('ix_swipehistory_user_id'), 'swipehistory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipehistory_user_id'), table_name='swipehistory')
    op.drop_index(op.f('ix_swipehistory_job_id'), table_name='swipehistory')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_job_id'), table_name='recommendations')
    op.drop_constraint('_user_job_recommendation_uc', 'recommendations', type_='unique')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_constraint('_user_job_application_uc', 'applications', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_token_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
