# Generated by Django 5.0.6 on 2026-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
