# Generated by Django 5.0.6 on 2026-09-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_type',
            field=models.CharField(choices=[('mnc', 'MNC'), ('startup', 'Startup'), ('new_startup', 'Newly founded startup'), ('unspecified', 'Not specified')], default='startup', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='fresher', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20),
        ),
    ]
