# Generated by Django 5.0.6 on 2026-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_company_type_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cleaned_description',
            field=models.TextField(blank=True),
        ),
    ]
