# Generated by Django 5.0.6 on 2026-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
