# Generated by Django 6.1 on 2026-08-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_candidateprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.BigIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("experience_level", models.CharField(blank=True, max_length=100)),
                ("contract_type", models.CharField(blank=True, max_length=100)),
                ("work_type", models.CharField(blank=True, max_length=100)),
                ("sector", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=150)),
                ("state", models.CharField(blank=True, max_length=150)),
                ("published_at", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
