# Generated by Django 6.1 on 2026-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
