# Generated by Django 6.1 on 2026-08-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_job_required_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="projects",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
