# Generated by Django 6.1 on 2026-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_resume_certifications_resume_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="requirements_extracted",
            field=models.BooleanField(default=False),
        ),
    ]
