# Generated by Django 6.1 on 2026-08-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_job_requirements_extracted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="certifications",
        ),
    ]
