# Generated by Django 6.1 on 2026-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_jobswipe_swipe_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobswipe",
            name="swipe_direction",
            field=models.CharField(
                choices=[("right", "Right"), ("left", "Left"), ("down", "save")],
                max_length=10,
            ),
        ),
    ]
