# Generated by Django 6.1 on 2026-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_jobswipe_swipe_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internship", "Internship"),
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="preferred_locations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
